
package view;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import model.Usuario;

public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }
    private Usuario usuario;
    
    MainForm(Usuario user) {
         this.usuario = user;
       initComponents(); // muy importante: primero esto
    
        // Solo si existen estos labels en tu diseño
        lblUsuario.setText("Bienvenido Usuario: " + usuario.getUsername());
        lblRol.setText("Rol"
                + ""
                + ": " + usuario.getRol());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        panelContenedor = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jMenuBarReportes = new javax.swing.JMenuBar();
        jMenuGestion = new javax.swing.JMenu();
        menuItemGestionPeliculas = new javax.swing.JMenuItem();
        MenuItemGestionFunciones = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuCerrarSesion = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setText("Nombre de Usuario:");

        lblRol.setText("Rol Ejercido:");

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 607, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
        );

        jMenuBarReportes.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuGestion.setText("GESTION");

        menuItemGestionPeliculas.setText("Películas ");
        menuItemGestionPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionPeliculasActionPerformed(evt);
            }
        });
        jMenuGestion.add(menuItemGestionPeliculas);

        MenuItemGestionFunciones.setText("Funciones");
        MenuItemGestionFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGestionFuncionesActionPerformed(evt);
            }
        });
        jMenuGestion.add(MenuItemGestionFunciones);

        jMenuItem4.setText("Salas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItem4);

        jMenuItem5.setText("Clientes");
        jMenuGestion.add(jMenuItem5);

        jMenuItem6.setText("Boletos");
        jMenuGestion.add(jMenuItem6);

        jMenuItem7.setText("Snacks");
        jMenuGestion.add(jMenuItem7);

        jMenuItem8.setText("Promociones ");
        jMenuGestion.add(jMenuItem8);

        jMenuBarReportes.add(jMenuGestion);

        jMenu2.setText("REPORTES");

        jMenuItem9.setText("Ventas por Dia");
        jMenu2.add(jMenuItem9);

        jMenuItem11.setText("Peliculas mas vistas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem10.setText("Clientes Frecuentes  ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem12.setText("Comparacion Salas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Reporte de Snacks Vendidos");
        jMenu2.add(jMenuItem13);

        jMenuBarReportes.add(jMenu2);

        jMenuConfiguracion.setText("CONFIGURACION");

        jMenuItem14.setText("Usuarios (gestión de cuentas/login)");
        jMenuConfiguracion.add(jMenuItem14);

        jMenuItem15.setText("Roles de Empleados");
        jMenuConfiguracion.add(jMenuItem15);

        jMenuItem16.setText("Empleados");
        jMenuConfiguracion.add(jMenuItem16);

        jMenuBarReportes.add(jMenuConfiguracion);

        jMenuCerrarSesion.setText("CERRAR SESION");
        jMenuBarReportes.add(jMenuCerrarSesion);

        setJMenuBar(jMenuBarReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemGestionPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionPeliculasActionPerformed
  
    menuItemGestionPeliculas.addActionListener(e -> mostrarPanelPeliculas());
    
    }//GEN-LAST:event_menuItemGestionPeliculasActionPerformed

    private void MenuItemGestionFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGestionFuncionesActionPerformed
     
    mostrarPanelFunciones();

    }//GEN-LAST:event_MenuItemGestionFuncionesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    private void mostrarPanelPeliculas() {
    panelContenedor.removeAll();
    panelContenedor.setLayout(new BorderLayout());

    PanelPeliculas panelPeliculas = new PanelPeliculas();
    panelContenedor.add(panelPeliculas, BorderLayout.CENTER);

    panelContenedor.revalidate();
    panelContenedor.repaint();
}
private void mostrarPanelFunciones() {
    panelContenedor.removeAll();
    panelContenedor.setLayout(new BorderLayout());

    PanelFunciones panelFunciones = new PanelFunciones();
    panelContenedor.add(panelFunciones, BorderLayout.CENTER);

    panelContenedor.revalidate();
    panelContenedor.repaint();
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemGestionFunciones;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarReportes;
    private javax.swing.JMenu jMenuCerrarSesion;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuItemGestionPeliculas;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
