
package view;
import util.Conexion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class PanelPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form PanelPeliculas
     */
    DefaultTableModel modelo;

    
    
    public PanelPeliculas() {
        initComponents();
        modelo = (DefaultTableModel) jTablePeliculas.getModel();
        
        jTablePeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        int fila = jTablePeliculas.getSelectedRow();
        if (fila != -1) {
            jTextFieldTitulo.setText(modelo.getValueAt(fila, 1).toString());
            jComboBoxIdioma.setSelectedItem(modelo.getValueAt(fila, 2).toString());
            jTextFieldDuracion.setText(modelo.getValueAt(fila, 3).toString());
            jComboBoxClasificacion.setSelectedItem(modelo.getValueAt(fila, 4).toString());
            jTextFieldDescripcion.setText(modelo.getValueAt(fila, 5).toString());
        }
    }
});
    cargarPeliculas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDuracion = new javax.swing.JTextField();
        jComboBoxIdioma = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxClasificacion = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeliculas = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1132, 748));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DESCRIPCION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 40));

        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });
        add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 490, 40));

        jLabel2.setText("IDIOMA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 70, 40));

        jLabel3.setText("TITULO");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 490, 40));

        jLabel4.setText("DURACION");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 40));

        jTextFieldDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDuracionActionPerformed(evt);
            }
        });
        add(jTextFieldDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 490, 40));

        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles", "Subtitulado en Español", "Subtitulado en Ingles" }));
        add(jComboBoxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 330, 40));

        jLabel5.setText("CLASIFICACION");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 130, 40));

        jComboBoxClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "A", "B", "B15", "C", "D" }));
        add(jComboBoxClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 330, 40));

        btnActualizar.setBackground(new java.awt.Color(0, 204, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, -1));

        btnRegistrar.setBackground(new java.awt.Color(51, 255, 51));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 160, -1));

        btnLimpiar.setBackground(new java.awt.Color(240, 222, 72));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 160, -1));

        jTablePeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Idioma", "Duracion ", "Clasificacion", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jTablePeliculas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1120, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDuracionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
    String titulo = jTextFieldTitulo.getText();
    String duracionStr = jTextFieldDuracion.getText();
    String descripcion = jTextFieldDescripcion.getText();
    String idioma = (String) jComboBoxIdioma.getSelectedItem();
    String clasificacion = (String) jComboBoxClasificacion.getSelectedItem();

    if (titulo.isEmpty() || duracionStr.isEmpty() || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.");
        return;
    }

    try (Connection conn = Conexion.getConexion()) {
        String sql = "INSERT INTO peliculas (titulo, idioma, duracion, clasificacion, descripcion) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, titulo);
        ps.setString(2, idioma);
        ps.setInt(3, Integer.parseInt(duracionStr));
        ps.setString(4, clasificacion);
        ps.setString(5, descripcion);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Película registrada correctamente.");

        cargarPeliculas();
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar película: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         int fila = jTablePeliculas.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una película para actualizar.");
        return;
    }

    int id = (int) modelo.getValueAt(fila, 0);
    String titulo = jTextFieldTitulo.getText();
    String duracionStr = jTextFieldDuracion.getText();
    String descripcion = jTextFieldDescripcion.getText();
    String idioma = (String) jComboBoxIdioma.getSelectedItem();
    String clasificacion = (String) jComboBoxClasificacion.getSelectedItem();

    try (Connection conn = Conexion.getConexion()) {
        String sql = "UPDATE peliculas SET titulo=?, idioma=?, duracion=?, clasificacion=?, descripcion=? WHERE id=?";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, titulo);
        ps.setString(2, idioma);
        ps.setInt(3, Integer.parseInt(duracionStr));
        ps.setString(4, clasificacion);
        ps.setString(5, descripcion);
        ps.setInt(6, id);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Película actualizada correctamente.");

        cargarPeliculas();
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar película: " + e.getMessage());
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          int fila = jTablePeliculas.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una película para eliminar.");
        return;
    }

    int id = (int) modelo.getValueAt(fila, 0);

    int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la película?", "Confirmar", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try (Connection conn = Conexion.getConexion()) {
            String sql = "DELETE FROM peliculas WHERE id=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, id);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Película eliminada correctamente.");

            cargarPeliculas();
            limpiarCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar película: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
            limpiarCampos();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    
    private void cargarPeliculas() {
    modelo.setRowCount(0); // Limpiar la tabla antes de recargar

    try (Connection conn = Conexion.getConexion()) {
        String sql = "SELECT * FROM peliculas";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] fila = {
                rs.getInt("id"),
                rs.getString("titulo"),
                rs.getString("idioma"),
                rs.getInt("duracion"),
                rs.getString("clasificacion"),
                rs.getString("descripcion")
            };
            modelo.addRow(fila);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar películas: " + e.getMessage());
    }
}

    private void limpiarCampos() {
    jTextFieldTitulo.setText("");
    jTextFieldDuracion.setText("");
    jTextFieldDescripcion.setText("");
    jComboBoxIdioma.setSelectedIndex(0);
    jComboBoxClasificacion.setSelectedIndex(0);
    jTablePeliculas.clearSelection();
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> jComboBoxClasificacion;
    private javax.swing.JComboBox<String> jComboBoxIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePeliculas;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
